version: '3.8'

services:
  minecraft-server:
    build: .
    image: itzg/minecraft-server
    container_name: vault-hunters
    environment:
      CF_API_KEY: '$2a$10$3iDVGIPkrjqtJTc3eBOKl.OrdzFTGRSClsmL0eElP8nRaqQKZF7pO'
      CF_CF_PAGE_URL: 'https://www.curseforge.com/minecraft/modpacks/vault-hunters-1-18-2/download/4687199'
      CF_SLUG: 'vault-hunters-1-18-2'
      EULA: 'TRUE'
      TYPE: 'AUTO_CURSEFORGE'
      VERSION: '1.18.2'
      MEMORY: '4G'
      ENABLE_ROLLING_LOGS: 'true'
    volumes:
      - ./data:/data
      - ./downloads:/downloads
    ports:
      - '25566:25565'
      - '19565:19565'
    restart: always
